package ru.stqa.pft.supertests;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class TeachingPageTest extends TestBase {

    @Test
    public void testTeachingPage() {

        getTeachPage();
    }
}
