package ru.stqa.pft.supertests.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.supertests.tests.TestBase;

public class TeachingPageTest extends TestBase {

    @Test
    public void testTeachingPage() {

        app.getTeachPage();
    }
}
